paths:
  public: "public"
groups:
  scripts:
    paths:
      - app/scripts
      - vendor
    concat:
      "/assets/scripts/app.js": "app/{scripts}/**/*.{js,coffee}"
      "/assets/scripts/vendor.js": "vendor/*.{js,coffee}"
    copy:
      "/assets/scripts": "vendor/ie/*.js"
    order:
      - "vendor/jquery.js"
      - "vendor/require_definition.js"
      - "vendor/handlebars.js"
      - "..."
      - vendor/jquery.ui.widget.js
      - vendor/jquery.iframe-transport.js
      - vendor/jquery.fileupload.js
      - "app/scripts/app.coffee"
  styles:
    paths:
      - app/styles
    concat:
      "/assets/styles/vendor.css": "vendor/*.{css,scss,sass}"
      "/assets/styles/app.css": "{app/styles/*.{css,scss,sass}}"
    copy:
      "/assets/styles": "{vendor/eevee/*.css,vendor/essage.css}"
    order:
      - "vendor/pokeball.css"
      - "vendor/base.css"
      - "..."
  images:
    paths:
      - app/images
    sprite:
      "../app/styles/icons.scss": "app/images/*.png"
    copy:
      "/assets/images/": "{app/images/**/*.jpg,app/images/other-images/*}"
  views:
    paths:
      - app/views
      - app/components_vendor
    copy:
      "/views": "app/views/**/*.hbs"
      "/components/": "{app/{components,components_vendor}/**/view.hbs,app/{components,components_vendor}/**/other_templates/*.hbs}"
  templates:
    paths:
      - "app/components"
      - "app/components_vendor"
    precompile:
      "../vendor/templates.js": "{app/components/**/templates/*.hbs,app/components_vendor/**/templates/*.hbs}"
  files:
    paths:
      - "app/files"
      - "app/font"
    copy:
      "/": "app/files/*"
      "/font": "app/font/*"
modules:
  wrapper: "cmd"
  ignored: "vendor/**/*"
  definition: "/scripts/app.js"
sprites:
  selector: ".icon-"
  path: "/assets/images/"
  url: "/assets/images/"
revision:
  prefix: ""
  manifest: "manifest.yml"
  files:
    - /views/layout.hbs
    - /views/eevee/editor.hbs
    - /views/eevee/wysiwyg.hbs
notification: true
bundles:
  "jquery.js":
    version: "master"
    url: "http://code.jquery.com/jquery-1.11.0.min.js"
  "bootstrap.min.css":
    version: "master"
    url: "http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css"
  "bootstrap.js":
    version: "master"
    url: "http://cdn.bootcss.com/bootstrap/3.3.1/js/bootstrap.js"
  essage.js:
    version: master
    url: https://raw.githubusercontent.com/sofish/essage/master/src/essage.js
  essage.css:
    version: master
    url: https://raw.githubusercontent.com/sofish/essage/master/src/essage.css

